import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const bpmf = localFont({
  src: "../public/fonts/BpmfZihiKaiStd.ttf",
  variable: "--font-bpmf",
});

const nunito = localFont({
  src: "../public/fonts/NunitoSans.ttf",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:"/icons/favicon.svg"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${bpmf.variable} ${nunito.variable}`}>
      <body className="antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}